server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name _;
    ssl_certificate /etc/nginx/certs/cloud1.crt;
    ssl_certificate_key /etc/nginx/certs/cloud1.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    resolver 127.0.0.11 valid=10s;
    root /var/www/html;
    index index.php;
    
    location ~ ^/phpmyadmin/(.+\.php)$ {
        set $upstream_pma phpmyadmin;
        fastcgi_pass $upstream_pma:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/$1;
    }
    location /phpmyadmin/ {
        alias /var/www/phpmyadmin/;
        try_files $uri $uri/ /phpmyadmin/index.php?$args;
    }
    location ~ \.php$ {
        set $upstream_wp wordpress;
        fastcgi_pass $upstream_wp:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
}
